### ISSUE TITLE
Still getting runtime.lastError Could not establish connection. Receiving end does not exist.

### ISSUE THREAD

**Issue by DNAMcKnight** [jpleboeuf/fcc_0n809nd4Zu4_chrome-extension-dev#1]
Hey, I don't know why but even with your code this error doesn't go away and yes I've read `in the manifest, "run_at" for `contentScript.js` set to "document_idle" instead of "document_start"`. And also the bookmark button on the player doesn't show up. I'm fairly new to JS and I decided to use this as a starting point and it seems to be a nightmare so far.

**Comment by jpleboeuf** [comment]
Hi, @DNAMcKnight,

thanks for the feedback, always welcome :)

+ That you get the error "Could not establish connection. Receiving end does not exist." is a bit strange, because it should be captured by [this line](https://github.com/jpleboeuf/fcc_0n809nd4Zu4_chrome-extension-dev/blob/main/src/background.js#L35). Can you send the logs from the service worker as generated by my version of the code? Or do you mean you see this message concatenated with "No listener, most probably the content script was loaded too late."? At the moment, I cannot reproduce that one, but it should not happen.
+ That the bookmark button sometimes doesn't show up, I can reproduce on a fresh install of Google Chrome (it seems that just refreshing the page makes it appear). I will investigate beginning of next week.

And I agree, it's a nightmare to debug, that's why I added heavy logging - but you can learn so much by trying to fix it!

Cheers!

**Comment by DNAMcKnight** [comment]
Hey, @jpleboeuf  thank you for the response. I appreciate you taking the time to help me out cause it seems you're the only help I have right now so it means a lot. Just to clarify I'm getting the console.log message 

`"ERROR: Could not establish connection. Receiving end does not exist.`
`=> No listener, most probably the content script was loaded too late."` 

so your error handler works as intended I don't see any log file. 

- But it seems the content script isn't running when it really should. Refreshing the page didn't help, the error persists and I don't seem to get the icon on the player for that reason. I am just about to reinstall chrome all together and see if that helps.

- Okay I deleted 90% of my comment lol. I managed to get your extension to work with Vivaldi browser. It seems something is wrong with my chrome bowser I don't know why but no matter what the error persists even with code from the documentation. I set `run_at` to `document_start` and now it works but if I refresh the page it doesn't work. 
![image](https://user-images.githubusercontent.com/31538687/184478458-cbefa7bb-534b-4087-aa8a-f67df1672e57.png)

`ALL GOOD: 'NEW' message received, and reception confirmed with 'NEW-ok'.` when I opened the new tab and 
`"ERROR: Could not establish connection. Receiving end does not exist.`
`=> No listener, most probably the content script was loaded too late."` 
when I reloaded the page.

I hope this isn't too much to ask but could you help me figure this out? just the reload not working bit, I can fix chrome as I go. Thank you for all that you do.

UPDATE!
After reinstalling Chrome it works however not without reloading the page. so basically now it's backwards reload works but not the new tab.

**Comment by jpleboeuf** [comment]
Thanks for the answer, @DNAMcKnight.

By logs, I was referring to the messages generated in the console, both from the service worker and the content script.

I'm confused with your explanation: when you write "even with code from the documentation", which documentation are you referring to?

Regarding your update, it seems like you ended up in a similar situation as in my last comment, that sometimes you have to reload for the bookmark button to appear.

I will try to debug this matter during the week, and I might explore further `run_at` in the manifest - though setting it to `document_start` was a big helper in solving the "Could not establish connection. Receiving end does not exist.", since it allows to have the content script available to receive messages from the service worker even before any other DOM is constructed (see "[Content scripts](https://developer.chrome.com/docs/extensions/mv3/content_scripts/)" in the "Chrome Developers" documentation, but you can also explore Stack Overflow on this tricky subject).

Cheers!

**Comment by DNAMcKnight** [comment]
I appreciate you taking your time to respond again @jpleboeuf Sorry for not being very clear with my answers. It's just too many things to write down cause I've tried so many things in the past week. Now things seem to be working as expected after the reinstall. If you can figure out why the reload is needed for it to work that would be helpful, I'm not stopping either, 

Like I mentioned the code from the documentation didn't work I'll try those again. Just to clarify, I specifically couldn't get `chrome.runtime.onMessage.addListener` to work without throwing the error `runtime.lastError Could not establish connection. Receiving end does not exist.` now that I'm past that I can continue to experiment with the doc and figure more things out all thanks to you! So I appreciate the effort you put in, it helps me keep trying to learn as well.

Cheers!
